# Generated by Django 5.1.3 on 2025-01-29 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_amount', models.FloatField()),
                ('discount_type', models.CharField(choices=[('percent', 'เปอร์เซ็นต์'), ('amount', 'บาท')], default='amount', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('hair_style', models.CharField(max_length=255)),
                ('hair_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('จองสำเร็จ', 'จองสำเร็จ'), ('ผู้ใช้ยกเลิก', 'ผู้ใช้ยกเลิก'), ('แอดมินยกเลิก', 'แอดมินยกเลิก')], default='จองสำเร็จ', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.promotion')),
            ],
        ),
    ]
