# Generated by Django 5.1.3 on 2025-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_customuser_options_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=6),
        ),
    ]
