# Generated by Django 5.1.3 on 2025-02-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
    ]
