# Generated by Django 5.1.3 on 2025-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('จองสำเร็จ', 'จองสำเร็จ'), ('ผู้ใช้ยกเลิก', 'ผู้ใช้ยกเลิก'), ('แอดมินยกเลิก', 'แอดมินยกเลิก'), ('เสร็จสิ้น', 'เสร็จสิ้น'), ('รีวิวเสร็จสิ้น', 'รีวิวเสร็จสิ้น')], default='จองสำเร็จ', max_length=50),
        ),
    ]
