# Generated by Django 5.1.3 on 2025-03-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
