# Generated by Django 5.1.3 on 2025-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('created', 'เพิ่มเสร็จแล้ว'), ('cancelled', 'ยกเลิกแล้ว')], default='created', max_length=10),
        ),
    ]
