# Generated by Django 5.1.3 on 2025-03-13 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.promotion'),
        ),
    ]
