# Generated by Django 5.1.3 on 2025-03-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyle',
            name='promotion',
        ),
    ]
