# Generated by Django 5.1.3 on 2025-03-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_hairstyle_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyle',
            name='promotion',
        ),
    ]
